### ISSUE TITLE
Failing to build on Ubuntu 20.04 with Cuda 11.4

### ISSUE THREAD

**Issue by onurbagoren** [NVlabs/instant-ngp#1222]
Hello, 

Whe I try to build using the `cmake --build build --config RelWithDebInfo` command, I get the following error, which I have been unable to resolve:

```
[ 14%] Built target fmt
[ 71%] Built target tiny-cuda-nn
[ 76%] Linking CXX executable ../mlp_learning_an_image
[ 80%] Linking CXX executable ../../bench_image_ours
/usr/bin/ld: CMakeFiles/mlp_learning_an_image.dir/mlp_learning_an_image.cu.o: in function `tcnn::CudaGraph::capture_guard(CUstream_st*)::{lambda()#1}::operator()() const':
tmpxft_00003c87_00000000-6_mlp_learning_an_image.cudafe1.cpp:(.text._ZZN4tcnn9CudaGraph13capture_guardEP11CUstream_stENKUlvE_clEv[_ZZN4tcnn9CudaGraph13capture_guardEP11CUstream_stENKUlvE_clEv]+0x393): undefined reference to `cudaGraphExecUpdate'
collect2: error: ld returned 1 exit status
make[2]: *** [samples/CMakeFiles/mlp_learning_an_image.dir/build.make:115: mlp_learning_an_image] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: samples/CMakeFiles/mlp_learning_an_image.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/bench_image_ours.dir/bench_ours.cu.o: in function `tcnn::CudaGraph::capture_guard(CUstream_st*)::{lambda()#1}::operator()() const':
tmpxft_00003c82_00000000-6_bench_ours.cudafe1.cpp:(.text._ZZN4tcnn9CudaGraph13capture_guardEP11CUstream_stENKUlvE_clEv[_ZZN4tcnn9CudaGraph13capture_guardEP11CUstream_stENKUlvE_clEv]+0x393): undefined reference to `cudaGraphExecUpdate'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/image/CMakeFiles/bench_image_ours.dir/build.make:115: bench_image_ours] Error 1
make[1]: *** [CMakeFiles/Makefile2:216: benchmarks/image/CMakeFiles/bench_image_ours.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I'm running on Ubuntu 20.04 and have Cuda 11.4 installed. Has anyone run into this, and been able to resolve it? Any help would be greatly appreciated!
