### ISSUE TITLE
Build on Windows CUDA 11.6.t argets(790,9):  error MSB3721

### ISSUE THREAD

**Issue by zxzxde** [NVlabs/instant-ngp#52]
Windows10
CUDA 11.6
RTX 3080TI
cmake 3.21.2
VS2019 14.29

\src\testbed.cu(1023): error : too few arguments in function cal
l [C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\build\ngp.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.6.t
argets(790,9): error MSB3721: “"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=
compute_86,code=\"compute_86,compute_86\" -gencode=arch=compute_86,code=\"sm_86,compute_86\" --use-local-env -ccbin "C:
\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu -rdc=true
 -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\dependencies" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gite
e\instant-ngp\dependencies\eigen" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\dependencies\filesystem" -
I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\dependencies\glfw\include" -I"C:\Users\Admin\PyOut\CGAI\insta
nt-ngp\Gitee\instant-ngp\dependencies\imgui\gl3w" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\dependenci
es\nanovdb" -I"C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.4.0\include" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gite
e\instant-ngp\dependencies\tiny-cuda-nn\include" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\dependencie
s\tiny-cuda-nn\dependencies" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\dependencies\tinylogger" -I"C:\
Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\include" -I"C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ng
p\build" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\RelWithDebInfo  -maxrr
egcount=0  --machine 64 --compile -cudart static --extended-lambda --expt-relaxed-constexpr -std=c++14 -Xcompiler="/EHs
c -Zi -Ob1 -bigobj"   -D_WINDOWS -DNDEBUG -DNGP_GUI -DNGP_OPTIX -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"NGP_VERSION=\"
1.0dev\"" -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -DWIN32 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -DNDEBUG -DNGP_GUI -
DNGP_OPTIX -DTCNN_MIN_GPU_ARCH=86 -DTCNN_SHAMPOO -D"NGP_VERSION=\"1.0dev\"" -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -Xcompi
ler "/EHsc /W1 /nologo /O2 /FdC:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\build\RelWithDebInfo\ngp.pdb /FS
/Zi  /MD /GR" -o ngp.dir\RelWithDebInfo\testbed.obj "C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\src\testbe
d.cu"” quit reture 1。 [C:\Users\Admin\PyOut\CGAI\instant-ngp\Gitee\instant-ngp\build\ngp.vcxproj]

**Comment by Tom94** [comment]
Your submodules are likely out of date.

Does 
```git submodule sync --recursive
git submodule update --recursive
```
resolve the problem?

**Comment by bit704** [comment]
I have the same error with you on 
Windows10
CUDA 11.2
RTX 3060
cmake 3.22.1
vs2019
But this error vanish when I use  RTX 3090.

**Comment by Tom94** [comment]
Please feel free to re-open the issue if updating the submodules as described above does not fix it.
