### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by psakamoori** [NVlabs/instant-ngp#802]
After installing all the pre-requisites and when trying to build on Ubuntu 20.04 I am getting below error...already spent two days trying to fig out whats the issues...it looks like "pthread" issue - But, stackoverflow and other channels say "pthread notfound" error is not the root cause of cmake fail...

Really appreciate any inputs on this...

/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d22a0.dir/link.txt --verbose=1
/usr/bin/cc CMakeFiles/cmTC_d22a0.dir/src.c.o -o cmTC_d22a0
/usr/bin/ld: CMakeFiles/cmTC_d22a0.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x5e): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x6f): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_d22a0.dir/build.make:99: cmTC_d22a0] Error 1
make[1]: Leaving directory '/home/psakamoori/AI/Projects/3DScene/instant-ngp/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_d22a0/fast] Error 2

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/psakamoori/AI/Projects/3DScene/instant-ngp/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_619af/fast && /usr/bin/make  -f CMakeFiles/cmTC_619af.dir/build.make CMakeFiles/cmTC_619af.dir/build
make[1]: Entering directory '/home/psakamoori/AI/Projects/3DScene/instant-ngp/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_619af.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_619af.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.20/Modules/CheckFunctionExists.c
Linking C executable cmTC_619af
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_619af.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_619af.dir/CheckFunctionExists.c.o -o cmTC_619af  -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_619af.dir/build.make:99: cmTC_619af] Error 1
make[1]: Leaving directory '/home/psakamoori/AI/Projects/3DScene/instant-ngp/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_619af/fast] Error 2

**Comment by psakamoori** [comment]
Realized that I am using cmake 3.20 version...updated cmake to 3.23.0 - But still the same error

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- The CUDA compiler identification is NVIDIA 11.0.194
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.0/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- No release type specified. Setting to 'Release'.
CMake Error at dependencies/tiny-cuda-nn/CMakeLists.txt:111 (list):
  list GET given empty list


-- Targeting GPU architectures: 
-- Module support is disabled.
-- Version: 9.0.0
-- Build type: Release
-- CXX_STANDARD: 14
-- Performing Test has_std_14_flag
-- Performing Test has_std_14_flag - Success
-- Performing Test has_std_1y_flag
-- Performing Test has_std_1y_flag - Success
-- Required features: cxx_variadic_templates
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so (found version "131") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using X11 for window creation
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found GLEW: /usr/include (found version "2.1.0") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- OptiX_INSTALL_DIR value: /home/psakamoori/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64
-- Found Python: /home/psakamoori/anaconda3/bin/python3.9 (found suitable version "3.9.12", minimum required is "3.7") found components: Interpreter Development Development.Module Development.Embed 
-- pybind11 v2.7.1 
CMake Warning (dev) at /usr/share/cmake-3.23/Modules/CMakeDependentOption.cmake:89 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  dependencies/pybind11/CMakeLists.txt:98 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring incomplete, errors occurred!
See also "/home/psakamoori/AI/Projects/3DScene/instant-ngp/build/CMakeFiles/CMakeOutput.log".
See also "/home/psakamoori/AI/Projects/3DScene/instant-ngp/build/CMakeFiles/CMakeError.log".

**Comment by dodgaga** [comment]
i have the same error as you. and if I dont't use python module, everything will be ok

**Comment by psakamoori** [comment]
@dodgaga  can you please elaborate - Did you do any modifications to CMakeList.txt. What is the fix/hack you used. thank you

**Comment by dodgaga** [comment]
hey! good news!  I have completed the build phase. Did you build the code in docker ?  the python related module seemly not success without the gui enviroment. You can try it in the local

**Comment by barissarpertezcan** [comment]
Hi there @dodgaga @psakamoori,
In the original post, it is stated that the build failed on an Ubuntu 20.04 system. I am using the same system and facing the same error, i.e., when I execute the second build command that is "cmake --build build --config RelWithDebInfo -j" my build gets stuck around 89% while trying to build "CXX Object CMakeFiles/ngp.dir/src/thread_pool.ccp.o" and my screen freezes. After about 5-10 minutes, the build fails with the CMakeError file indicating lpthreads library is missing, which is obviously not the case but a cmake bug. Also, I tried commenting the src/thread_pool.cpp line in list(APPEND NGP_SOURCES ...) in CMakeFile to be able to find the real problem behind the scene yet not even succeeded fail the build, i.e, the build just stuck around 36% and screen froze about half an hour and I had to terminate the build, so I got no log file. Moreover, I tried to run the first build command without the gui option (cmake . -B build -DNGP_BUILD_WITH_GUI=OFF) but got stuck again at 36% in the second build command.

My settings: 
CUDA version: 11.7
GPU: GeForce GTX 1650 Mobile / Max-Q
cmake version: 3.22.1
g++ version: 9.4.0
gcc version: 9.4.0

What is your opinion about the reason or the possible cause of that error? Any help is appreciated.

**Comment by psakamoori** [comment]
@dodgaga Good for you...But, Please share your Docker file :) .

**Comment by psakamoori** [comment]
@barissarpertezcan  where was it given that build fails on Ubuntu 20.04?

**Comment by psakamoori** [comment]
@barissarpertezcan  

Finally...Below line fixed the build issue

set(CMAKE_CUDA_ARCHITECTURES 86)

add above to to "dependencies/tiny-cuda-nn/CMakeLists.txt"  at line 111

as shown below
# Sort the list to obtain lowest architecture that must be compiled for.
list(SORT CMAKE_CUDA_ARCHITECTURES COMPARE NATURAL ORDER ASCENDING)
set(CMAKE_CUDA_ARCHITECTURES 86)
list(GET CMAKE_CUDA_ARCHITECTURES 0 MIN_GPU_ARCH)

Ref: https://github.com/NVlabs/instant-ngp/issues/426
